name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        mode: [release, dev]
        go: ["1.14"]

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install prerequisites (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build deej (Windows)
        if: runner.os == 'Windows'
        run: pkg/deej/scripts/windows/build-${{ matrix.mode }}.bat
        shell: cmd

      - name: Upload a build artifact (Windows)
        uses: actions/upload-artifact@v4.6.1
        if: runner.os == 'Windows'
        with:
          name: deej-${{ matrix.mode }}
          path: deej-${{ matrix.mode }}.exe

      - name: Build deej (Linux)
        if: runner.os == 'Linux'
        run: pkg/deej/scripts/linux/build-${{ matrix.mode }}.sh

      - name: Upload a build artifact (Linux)
        uses: actions/upload-artifact@v4.6.1
        if: runner.os == 'Linux'
        with:
          name: deej-${{ matrix.mode }}
          path: deej-${{ matrix.mode }}
